baseurl = "/"
languageCode = "en-us"
title = "Blog-m4xx"
theme = "hello-friend"
copyright = ""
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  subtitle = ""
  # "light" or "dark"
  defaultTheme = "dark"

[params.logo]
  logoText = "hello friend"
  # or
  #
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/proj/1"   
  [[menu.main]]
    identifier = "tutorials"
    name = "Tutorials"
    url = "/tuts/shell_script"
 [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"

[languages]
  [languages.en]
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"